#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  colorscheme = "dracula/vim" 
  colorscheme_bg = "dark"
  enable_guicolors = false
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  statusline_unicode_symbols = true 
  vimcompatible = true
  bootstrap_after = "bootstrap#after"
  filemanager = "nerdtree"

[[custom_plugins]]
  name = "dracula/vim"

[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'fzf'

[[layers]]
  name = 'git'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#javascript'

[[layers]]
  name = 'lang#markdown'

[[layers]]
  name = 'lang#php'

[[layers]]
  name = 'lang#python'

[[layers]]
  name = 'lang#graphql'

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = 'lang#typescript'

[[layers]]
  name = 'test'

[[layers]]
  name = 'github'

[[layers]]
  name = 'indentmove'
